---
shared:
  notion:
    deal_events:
      type: event
      properties:
      - entity_id:
          type: uuid
      - database_id:
          type: uuid
      - workspace_id:
          type: uuid
      required:
      - entity_id
      - database_id
      - workspace_id
      - workspace_name
    vendor_events:
      type: event
      properties:
      - entity_id:
          type: uuid
      - database_id:
          type: uuid
      required:
      - entity_id
      - database_id
