# TODO: [LWS-309] Templatize this file and have `lx-cli env-setup` handle generating it for different environments
#   based on a template and environment-specific .env files that are the source of truth for environment
#   variables. This would help reduce duplication and make it easier to manage environment variables
#   across different environments.
services:
  mailhog:
    container_name: mailhog.cami.larcity
    image: mailhog/mailhog
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "16545:1025"
      - "16585:8025"
    profiles:
      - batteries-included
      - all

  redis:
    container_name: redis.cami.larcity
    image: redis
    restart: always
    command: ["--maxmemory-policy", "noeviction"]
    ports:
      - "16079:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    profiles:
      - all
      - batteries-included
      - essential

  # Doc: https://ngrok.com/docs/using-ngrok-with/docker/#:~:text=Using%20ngrok%20with%20Docker%20Compose
  tunnel:
    container_name: ngrok.cami.larcity
    image: ngrok/ngrok
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}
      NGROK_CONFIG: /etc/ngrok.yml
    command:
      # CLI docs: https://ngrok.com/docs/agent/cli/#ngrok-start
      - "start"
      - "--all"
    volumes:
      # Be sure to run bin/thor lx-cli:tunnel:init to generate the ngrok.yml file
      - ./config/ngrok-via-docker.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    profiles:
      - all

  app-store:
    container_name: db.cami.larcity
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${APP_DATABASE_NAME_PRIMARY}
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
      APP_DATABASE_NAME_CRM: ${APP_DATABASE_NAME_CRM}
      POSTGRES_HOST_AUTH_METHOD: trust # IMPORTANT allows all connections without a password - experimental only!
    ports:
      - "16032:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/shared/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./db/${RAILS_ENV:-development}/postgres/downloads:/usr/local/downloads:ro
    healthcheck:
      test: pg_isready -U ${APP_DATABASE_USER} -h localhost -d ${APP_DATABASE_NAME_PRIMARY}
      interval: 5s
      timeout: 5s
      retries: 10
    profiles:
      - batteries-included
      - essential
      - standalone
      - all

  web:
    container_name: web.cami.larcity
    image: larcity/accounts-web
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        - RAILS_ENV=${RAILS_ENV:-development}
        - APP_DATABASE_USER=${APP_DATABASE_USER}
        - APP_DATABASE_PASSWORD=${APP_DATABASE_PASSWORD}
        - APP_DATABASE_NAME_PRIMARY=${APP_DATABASE_NAME_PRIMARY}
        - GITCRYPT_KEY_BASE64=${GITCRYPT_KEY_BASE64}
        - SMTP_USER=${SMTP_USER}
        - PAYPAL_API_BASE_URL=${PAYPAL_API_BASE_URL}
        - PAYPAL_BASE_URL=${PAYPAL_BASE_URL}
        - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
        - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
        - ZOHO_CLIENT_ID=${ZOHO_CLIENT_ID}
        - ZOHO_CLIENT_SECRET=${ZOHO_CLIENT_SECRET}
        - CRM_ORG_ID=${CRM_ORG_ID}
      secrets:
        - source: gitcrypt-key
          target: gitcrypt.key
        - source: development-key
          target: development.key
        - source: production-key
          target: production.key
        - source: lab-key
          target: lab.key
    restart: unless-stopped
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      APP_CONFIG_CHECK_ENV_VARS: yes
      APP_DATABASE_HOST: db.cami.larcity
      APP_DATABASE_NAME_PRIMARY: ${APP_DATABASE_NAME_PRIMARY}
      APP_DATABASE_USER: ${APP_DATABASE_USER}
      APP_DATABASE_PASSWORD: ${APP_DATABASE_PASSWORD}
      GITCRYPT_KEY_BASE64: ${GITCRYPT_KEY_BASE64}
      SMTP_USER: ${SMTP_USER}
    secrets:
      - source: gitcrypt-key
        target: gitcrypt.key
      - source: development-key
        target: development.key
      - source: production-key
        target: production.key
      - source: lab-key
        target: lab.key
    volumes:
      - ./config/credentials/git-crypt.key:/opt/project/src/.git/git-crypt/keys/default:ro
      - ./config/credentials/$RAILS_ENV.yml.enc:/opt/project/src/config/credentials.yml.enc:ro
    ports:
      - "16006:3000"
    depends_on:
      - app-store
    profiles:
      - batteries-included
      - standalone
      - all

  worker:
    container_name: worker.cami.larcity
    image: larcity/accounts-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
      secrets:
        - source: gitcrypt-key
          target: gitcrypt.key
        - source: development-key
          target: development.key
        - source: production-key
          target: production.key
        - source: lab-key
          target: lab.key
    restart: unless-stopped
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      APP_CONFIG_CHECK_ENV_VARS: yes
      APP_DATABASE_HOST: db.cami.larcity
      APP_DATABASE_NAME_PRIMARY: ${APP_DATABASE_NAME_PRIMARY}
      APP_DATABASE_USER: ${APP_DATABASE_USER}
      APP_DATABASE_PASSWORD: ${APP_DATABASE_PASSWORD}
      GITCRYPT_KEY_BASE64: ${GITCRYPT_KEY_BASE64}
      SMTP_USER: ${SMTP_USER}
    secrets:
      - source: gitcrypt-key
        target: gitcrypt.key
      - source: development-key
        target: development.key
      - source: production-key
        target: production.key
      - source: lab-key
        target: lab.key
    volumes:
      - ./config/credentials/git-crypt.key:/opt/project/src/.git/git-crypt/keys/default:ro
      - ./config/credentials/$RAILS_ENV.yml.enc:/opt/project/src/config/credentials.yml.enc:ro
    depends_on:
      - app-store
    profiles:
      - batteries-included
      - standalone
      - all

  crm-app:
    container_name: twenty-server.cami.larcity
    image: twentycrm/twenty:v2
    volumes:
      - server_local_data:/app/packages/twenty-server/.local-storage
    ports:
      - "${CRM_SERVICE_PORT:-16016}:3000"
    environment:
      NODE_PORT: 3000
      PG_DATABASE_URL: postgres://${APP_DATABASE_USER:-postgres}:${APP_DATABASE_PASSWORD:-postgres}@db.cami.larcity:${CRM_DATABASE_PORT:-5432}/${APP_DATABASE_NAME_CRM:-default}
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: ${CRM_REDIS_URL:-redis://redis:6379}
      DISABLE_DB_MIGRATIONS: ${DISABLE_DB_MIGRATIONS}
      DISABLE_CRON_JOBS_REGISTRATION: ${DISABLE_CRON_JOBS_REGISTRATION}

      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}

      APP_SECRET: ${APP_SECRET:-replace_me_with_a_random_string}
      # MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED}
      # CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}
      # AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      # AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
      # AUTH_GOOGLE_CALLBACK_URL: ${AUTH_GOOGLE_CALLBACK_URL}
      # AUTH_GOOGLE_APIS_CALLBACK_URL: ${AUTH_GOOGLE_APIS_CALLBACK_URL}

      # CALENDAR_PROVIDER_MICROSOFT_ENABLED: ${CALENDAR_PROVIDER_MICROSOFT_ENABLED}
      # MESSAGING_PROVIDER_MICROSOFT_ENABLED: ${MESSAGING_PROVIDER_MICROSOFT_ENABLED}
      # AUTH_MICROSOFT_ENABLED: ${AUTH_MICROSOFT_ENABLED}
      # AUTH_MICROSOFT_CLIENT_ID: ${AUTH_MICROSOFT_CLIENT_ID}
      # AUTH_MICROSOFT_CLIENT_SECRET: ${AUTH_MICROSOFT_CLIENT_SECRET}
      # AUTH_MICROSOFT_CALLBACK_URL: ${AUTH_MICROSOFT_CALLBACK_URL}
      # AUTH_MICROSOFT_APIS_CALLBACK_URL: ${AUTH_MICROSOFT_APIS_CALLBACK_URL}

      # EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-contact@yourdomain.com}
      # EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-"John from YourDomain"}
      # EMAIL_SYSTEM_ADDRESS: ${EMAIL_SYSTEM_ADDRESS:-system@yourdomain.com}
      # EMAIL_DRIVER: ${EMAIL_DRIVER:-smtp}
      # EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-smtp.gmail.com}
      # EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-465}
      # EMAIL_SMTP_USER: ${EMAIL_SMTP_USER:-}
      # EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD:-}

    restart: unless-stopped
    depends_on:
      app-store:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 5s
      timeout: 5s
      retries: 20
    profiles:
      - all
      - batteries-included
      - essential

  crm-worker:
    container_name: twenty-worker.cami.larcity
    image: twentycrm/twenty:v2
    volumes:
      - server_local_data:/app/packages/twenty-server/.local-storage
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://${APP_DATABASE_USER:-postgres}:${APP_DATABASE_PASSWORD:-postgres}@db.cami.larcity:${CRM_DATABASE_PORT:-5432}/${APP_DATABASE_NAME_CRM:-default}
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: ${CRM_REDIS_URL:-redis://redis:6379}
      DISABLE_DB_MIGRATIONS: "true" # it already runs on the server
      DISABLE_CRON_JOBS_REGISTRATION: "true" # it already runs on the server

      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}

      APP_SECRET: ${APP_SECRET:-replace_me_with_a_random_string}
      # MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED}
      # CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}
      # AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      # AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
      # AUTH_GOOGLE_CALLBACK_URL: ${AUTH_GOOGLE_CALLBACK_URL}
      # AUTH_GOOGLE_APIS_CALLBACK_URL: ${AUTH_GOOGLE_APIS_CALLBACK_URL}

      # CALENDAR_PROVIDER_MICROSOFT_ENABLED: ${CALENDAR_PROVIDER_MICROSOFT_ENABLED}
      # MESSAGING_PROVIDER_MICROSOFT_ENABLED: ${MESSAGING_PROVIDER_MICROSOFT_ENABLED}
      # AUTH_MICROSOFT_ENABLED: ${AUTH_MICROSOFT_ENABLED}
      # AUTH_MICROSOFT_CLIENT_ID: ${AUTH_MICROSOFT_CLIENT_ID}
      # AUTH_MICROSOFT_CLIENT_SECRET: ${AUTH_MICROSOFT_CLIENT_SECRET}
      # AUTH_MICROSOFT_CALLBACK_URL: ${AUTH_MICROSOFT_CALLBACK_URL}
      # AUTH_MICROSOFT_APIS_CALLBACK_URL: ${AUTH_MICROSOFT_APIS_CALLBACK_URL}

      # EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-contact@yourdomain.com}
      # EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-"John from YourDomain"}
      # EMAIL_SYSTEM_ADDRESS: ${EMAIL_SYSTEM_ADDRESS:-system@yourdomain.com}
      # EMAIL_DRIVER: ${EMAIL_DRIVER:-smtp}
      # EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-smtp.gmail.com}
      # EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-465}
      # EMAIL_SMTP_USER: ${EMAIL_SMTP_USER:-}
      # EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD:-}

    restart: unless-stopped
    depends_on:
      app-store:
        condition: service_healthy
      crm-app:
        condition: service_healthy
    profiles:
      - all
      - batteries-included
      - essential

volumes:
  postgres_data:
  server_local_data:

secrets:
  gitcrypt-key:
    file: ./config/credentials/git-crypt.key
  development-key:
    file: ./config/credentials/development.key
  staging-key:
    file: ./config/credentials/staging.key
  production-key:
    file: ./config/credentials/production.key
  lab-key:
    file: ./config/credentials/lab.key

networks:
  default:
    name: larcity_apps
    enable_ipv6: false
    driver: bridge
