FROM ruby:3.4.4 AS base
# Install git-crypt and other dependencies
RUN apt-get update -qq && \
  apt-get install -y --no-install-recommends \
  build-essential \
  git-crypt \
  pkg-config \
  libvips \
  libpq-dev \
  && rm -rf /var/lib/apt/lists/*

FROM base AS src
ENV WORKDIR="/opt/project/src"
RUN mkdir -p $WORKDIR
# Set up your app directory
WORKDIR $WORKDIR
# Copy the source code into the container
COPY . .

FROM src AS web
# Run your build script (the one we made in the previous step)
RUN ./bin/build

# Review Render docs on building from a Dockerfile:
# https://render.com/docs/docker#building-from-a-dockerfile
EXPOSE 3000

# Specify the entrypoint command to run your Rails server
CMD ["bundle", "exec", "rails", "server", "--binding", "0.0.0.0"]
