# Exported from Render on 2025-12-11T12:40:07Z
version: "1"
projects:
  - name: CAMI(S) - Customer Account Management & Invoicing System
    environments:
      - name: Production
        # The Rails application database
        databases:
          - name: cami-production-db
            databaseName: sails_production
            user: sails_production_user
            plan: basic-256mb
            region: virginia
            ipAllowList:
              - source: 0.0.0.0/0
                description: everywhere
            postgresMajorVersion: "17"
            diskSizeGB: 1
        services:
          # The Rails web application
          - type: web
            name: cami-production-app
            runtime: docker
            repo: https://github.com/uchilaka/cami-ritv
            branch: releases/production
            plan: starter
            envVars:
              - key: RAILS_MASTER_KEY
                sync: false
              - key: PORT
                sync: false
              - key: HOSTNAME
                sync: false
              - key: RAILS_MAX_THREADS
                sync: false
              - key: RAILS_MIN_THREADS
                sync: false
              - key: RAILS_QUEUE_THREADS
                sync: false
              - key: NODE_ENV
                sync: false
              - key: WEB_CONCURRENCY
                sync: false
              - key: APP_DATABASE_HOST
                fromDatabase:
                  name: cami-production-db
                  property: host
              - key: APP_PRIMARY_DATABASE_NAME
                fromDatabase:
                  name: cami-production-db
                  property: database
              - key: APP_DATABASE_USER
                fromDatabase:
                  name: cami-production-db
                  property: user
              - key: APP_DATABASE_PASSWORD
                fromDatabase:
                  name: cami-production-db
                  property: password
              - fromGroup: Logtail Production
              - fromGroup: CRM Production
              # - fromGroup: Database Production
              - fromGroup: PayPal Production
              - fromGroup: SMTP Live
              - fromGroup: Vault Shared
            region: virginia
            preDeployCommand: ./bin/worker-pre-deploy
            dockerContext: .
            dockerfilePath: ./Dockerfile.web
            domains:
              - accounts.lar.city
              - accounts.larcity.tech
            # Trigger initially set to checksPass to ensure that the application only auto-deploys
            # when all health checks are passing. This is especially important for the production
            # environment to prevent deploying potentially broken code.
            autoDeployTrigger: checksPass
            previews:
              generation: manual
              numInstances: 1
          # The background worker for processing async jobs
          - type: worker
            name: cami-production-solid-queue
            runtime: docker
            repo: https://github.com/uchilaka/cami-ritv
            branch: releases/production
            plan: starter
            envVars:
              - key: RAILS_MASTER_KEY
                sync: false
              #- key: PORT
              #  sync: false
              #- key: HOSTNAME
              #  sync: false
              - key: RAILS_MAX_THREADS
                sync: false
              - key: RAILS_MIN_THREADS
                sync: false
              - key: RAILS_QUEUE_THREADS
                sync: false
              - key: NODE_ENV
                sync: false
              - key: WEB_CONCURRENCY
                sync: false
              - key: APP_DATABASE_HOST
                fromDatabase:
                  name: cami-production-db
                  property: host
              - key: APP_PRIMARY_DATABASE_NAME
                fromDatabase:
                  name: cami-production-db
                  property: database
              - key: APP_DATABASE_USER
                fromDatabase:
                  name: cami-production-db
                  property: user
              - key: APP_DATABASE_PASSWORD
                fromDatabase:
                  name: cami-production-db
                  property: password
              - fromGroup: Logtail Production
              - fromGroup: CRM Production
              # - fromGroup: Database Production
              - fromGroup: PayPal Production
              - fromGroup: SMTP Live
              - fromGroup: Vault Shared
            region: virginia
            preDeployCommand: ./bin/worker-pre-deploy
            dockerContext: .
            dockerfilePath: ./Dockerfile.web
            autoDeployTrigger: checksPass

      - name: Staging
        # The Rails (staging) application database
        databases:
          - name: cami-staging-db
            databaseName: sails_staging
            user: sails_staging_user
            plan: free
            region: virginia
            ipAllowList:
              - source: 0.0.0.0/0
                description: everywhere
            postgresMajorVersion: "17"
        # See documentation on referencing values from other services:
        # https://render.com/docs/blueprint-spec#referencing-values-from-other-services
        services:
          # The Rails (staging) application
          - type: web
            name: cami-staging-app
            runtime: docker
            repo: https://github.com/uchilaka/cami-ritv
            branch: releases/staging
            plan: free
            envVars:
              - key: HOSTNAME
                sync: false
              - key: RAILS_ENV
                sync: false
              - key: WEB_CONCURRENCY
                sync: false
              - fromGroup: CRM Staging
              - fromGroup: Logtail Staging
              - fromGroup: PayPal Staging
              - fromGroup: SMTP Live
              - fromGroup: Vault Shared
              - key: APP_DATABASE_HOST
                fromDatabase:
                  name: cami-staging-db
                  property: host
              - key: APP_PRIMARY_DATABASE_NAME
                fromDatabase:
                  name: cami-staging-db
                  property: database
              - key: APP_DATABASE_USER
                fromDatabase:
                  name: cami-staging-db
                  property: user
              - key: APP_DATABASE_PASSWORD
                fromDatabase:
                  name: cami-staging-db
                  property: password
            region: virginia
            preDeployCommand: ./bin/worker-pre-deploy
            dockerContext: .
            dockerfilePath: ./Dockerfile.web
            autoDeployTrigger: commit
          # The Rails (staging) background worker for processing async jobs
#          - type: worker
#            name: cami-staging-solid-queue
#            runtime: docker
#            repo: https://github.com/uchilaka/cami-ritv
#            branch: releases/staging
#            plan: starter
#            envVars:
#              - key: HOSTNAME
#                sync: false
#              - key: RAILS_ENV
#                sync: false
#              - key: WEB_CONCURRENCY
#                sync: false
#              - fromGroup: CRM Staging
#              - fromGroup: Logtail Staging
#              - fromGroup: PayPal Staging
#              - fromGroup: SMTP Live
#              - fromGroup: Vault Shared
#              - key: APP_DATABASE_HOST
#                fromDatabase:
#                  name: cami-staging-db
#                  property: host
#              - key: APP_PRIMARY_DATABASE_NAME
#                fromDatabase:
#                  name: cami-staging-db
#                  property: database
#              - key: APP_DATABASE_USER
#                fromDatabase:
#                  name: cami-staging-db
#                  property: user
#              - key: APP_DATABASE_PASSWORD
#                fromDatabase:
#                  name: cami-staging-db
#                  property: password
#            region: virginia
#            preDeployCommand: ./bin/worker-pre-deploy
#            dockerContext: .
#            dockerfilePath: ./Dockerfile.worker
#            autoDeployTrigger: commit
