# frozen_string_literal: true

require 'lar_city/cli/utils'

module LarCity
  module CLI
    # Set up the baseline .env file for loading application secrets
    class EnvSetupCmd < Thor::Group
      namespace :'env-setup'

      no_commands do
        include ::LarCity::CLI::EnvHelpers
        include ::LarCity::CLI::IoHelpers
        include ::LarCity::CLI::OutputHelpers
        include ::LarCity::CLI::Runnable
      end

      define_output_options self, class_options: true

      # --- Sequential steps ---
      def debug_template_file_content
        say_debug <<~DEBUG_MSG

          ******************************************************************
          ******* ENV Template Content (for <project-root>/.env.tpl) *******
          ******************************************************************
          #{template_content}
        DEBUG_MSG
      end

      def write_template_file
        say_info "Writing .env template file to #{template_file_path}..."
        return if pretend?

        bytes_written = File.write template_file_path, template_content
        say_debug <<~DEBUG_MSG
          Result of writing .env template file to #{template_file_path}: #{bytes_written.inspect}
        DEBUG_MSG
        if bytes_written.positive?
          say_success "Successfully wrote .env template file to #{template_file_path}."
        else
          say_error "Failed to write .env template file to #{template_file_path}."
        end
      end

      def provision_env_file_from_template
        require_template_exists!
        require_proton_pass_cli!

        say_info "Provisioning .env file from template at #{template_file_path}..."
        run(
          'pass-cli inject',
          "--in-file #{template_file_path}",
          "--out-file #{output_file_path}",
          '--force'
        ) do |line|
          say_debug line
        end
      end

      no_commands do
        def template_content
          @template_content ||=
            begin
              say_debug <<~DEBUG_MSG
                Fetching environment variable values from Proton Vault to
                initialize the .env.tpl template and generate the .env file
                for the app.

                =======================================================================
                ======== IMPORTANT: Ensure Proton Vault Access and Permissions ========
                =======================================================================
                To successfully fetch the required environment variable values, start
                by verifying that you have the necessary access and permissions in
                Proton Vault. You can sign in by running: `pass-cli login`

                Source Item ID: #{source_item_id}
                Vault Share ID: #{vault_share_id}
                Template path: #{template_file_path}
              DEBUG_MSG

              file_header = <<~HEADER
                # This file is auto-generated from .env.tpl using secrets stored
                # in Proton Vault.
                #
                # To update the secrets, modify the corresponding item in the
                # Proton Vault and re-run this command.
                #
                # Do NOT edit this file directly, as changes will be overwritten.
                # -----------------------------------------------------------------
                # Last generated at: #{Time.current.iso8601}
                # -----------------------------------------------------------------
                export GITCRYPT_KEY_FILE="config/credentials/git-crypt.key"
                export PORT=16006
              HEADER

              database_header = '# Dockerized database credentials'

              file_footer = <<~FILE_FOOTER

                export DEFAULT_EMAIL_SENDER="do-not-reply@larcity.tech"
                export INVOICING_EMAIL_SENDER="invoicing@lar.city"
                export MARKETING_EMAIL_SENDER="info@lar.city"

                #export SEMANTIC_LOGGER_STREAMING_ENABLED="yes"
                export BETTERSTACK_INGESTION_HOST=#{Rails.application.credentials.betterstack.ingestion_host!}
              FILE_FOOTER

              erb_template_array = [file_header, database_header]

              # Provision database ENV variables from Proton Vault
              database_env_sets.each do |env_key, vault_field, group|
                erb_template_array <<
                  "export #{env_key}=\"{{ pass://#{value_path(vault_share_id, source_item_id, group, vault_field)} }}\""
              end

              erb_template_array << ''

              # Provision secrets from ENV variable item in Proton Vault
              item_env_sets.each do |env_key, vault_field, group|
                erb_template_array <<
                  "export #{env_key}=\"{{ pass://#{value_path(vault_share_id, source_item_id, group, vault_field)} }}\""
              end

              erb_template_array << file_footer

              # Return formatted ERB template content as a string
              "#{erb_template_array.join("\n")}\n"
            end
        end

        private

        def value_path(*segments)
          segments.compact.join('/')
        end

        def require_proton_pass_cli!
          return if run('which pass-cli > /dev/null 2>&1', inline: true)

          say_error 'Proton CLI (pass-cli) is not installed or not found in PATH. Please install it to fetch secrets from Proton Vault.'
          raise Thor::Error, 'Proton CLI (pass-cli) is required but not found in PATH.'
        end

        def require_template_exists!
          return if File.exist?(template_file_path)

          say_error "Template file not found at #{template_file_path}. Cannot provision .env file without template."
          raise Thor::Error, "Template file not found at #{template_file_path}"
        end

        def database_env_sets
          [
            ['APP_DATABASE_USER', 'Database username'],
            ['APP_DATABASE_PASSWORD', 'Database password'],
          ]
        end

        def item_env_sets
          [
            ['RENDER_WORKSPACE_ID', 'Render Workspace ID'],
            ['APP_DEPLOY_PRODUCTION_HOOK_URL', 'Production Deploy Hook URL'],
            ['APP_DEPLOY_STAGING_HOOK_URL', 'Staging Deploy Hook URL'],
          ]
        end

        def vault_share_id
          proton_credentials.vault_share_id
        end

        def source_item_id
          proton_credentials.env_vars_item_id
        end

        def proton_credentials
          @proton_credentials ||= Rails.application.credentials.proton!
        end

        def output_file_path
          @output_file_path ||= Rails.root.join(output_filename).to_s
        end

        def output_filename
          @output_filename ||= ['.env', Rails.env, 'local'].join('.')
        end

        def template_file_path
          @template_path ||= Rails.root.join('.env.tpl').to_s
        end
      end
    end
  end
end
