---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/form_data/countries":
    get:
      summary: Retrieves a list of countries
      tags:
      - Form Data
      responses:
        '200':
          description: countries found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/country"
  "/api/v1/form_data/countries_map":
    get:
      summary: Retrieves a map of countries
      tags:
      - Form Data
      responses:
        '200':
          description: countries map found
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  "$ref": "#/components/schemas/country_mapped"
  "/api/v1/invoices/search.json":
    post:
      summary: Retrieves all invoices
      tags:
      - Invoices
      parameters: []
      responses:
        '200':
          description: invoices found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/invoice"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/invoice_search_params"
              - "$ref": "#/components/schemas/invoice_search_params_with_array_mode"
  "/invoices/search.json":
    post:
      summary: Retrieves all invoices
      tags:
      - Invoices
      parameters: []
      responses:
        '200':
          description: invoices found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/invoice"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/invoice_search_params"
              - "$ref": "#/components/schemas/invoice_search_params_with_array_mode"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: accounts.larcity.local
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
    basic_auth:
      type: http
      scheme: basic
  schemas:
    notion_entity:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          pattern: "^(page|database|person|block)$"
      required:
      - id
      - type
    notion_block:
      "$ref": "#/components/schemas/notion_entity"
    notion_event:
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
          format: date-time
        workspace_id:
          type: string
        workspace_name:
          type: string
        subscription_id:
          type: string
        integration_id:
          type: string
        attempt_number:
          type: integer
        authors:
          type: array
          items:
            "$ref": "#/components/schemas/notion_entity"
        data:
          type: object
          properties:
            parent:
              "$ref": "#/components/schemas/notion_entity"
            updated_blocks:
              type: array
              nullable: true
              items:
                "$ref": "#/components/schemas/notion_block"
          required:
          - parent
        type:
          type: string
          pattern: "^(page\\.(created|content_updated|deleted|moved|properties_updated)|database\\.(content_updated|schema_updated|deleted))$"
        entity:
          "$ref": "#/components/schemas/notion_entity"
      required:
      - id
      - data
      - type
      - integration_id
      - attempt_number
    account:
      type: object
      properties:
        id:
          type: string
        displayName:
          type: string
        email:
          type: string
        status:
          type: string
        taxId:
          type: string
          nullable: true
        type:
          type: string
      required:
      - id
      - displayName
      - email
      - status
    contact:
      type: object
      properties:
        displayName:
          type: string
        familyName:
          type: string
        givenName:
          type: string
        email:
          type: string
        type:
          type: string
      required:
      - displayName
      - email
    money:
      type: object
      properties:
        currencyCode:
          type: string
        formattedValue:
          type: string
        value:
          type: number
        valueInCents:
          type: integer
      required:
      - currencyCode
      - formattedValue
      - value
      - valueInCents
    invoice:
      type: object
      properties:
        id:
          type: string
        account:
          allOf:
          - "$ref": "#/components/schemas/account"
          nullable: true
        contacts:
          type: array
          items:
            "$ref": "#/components/schemas/contact"
        status:
          type: string
        invoiceNumber:
          type: string
        currencyCode:
          type: string
        createdAt:
          type: string
          format: date-time
        dueAt:
          type: string
          format: date-time
          nullable: true
        paidAt:
          type: string
          format: date-time
          nullable: true
        amount:
          "$ref": "#/components/schemas/money"
        dueAmount:
          "$ref": "#/components/schemas/money"
        paymentVendorURL:
          type: string
      required:
      - id
      - account
      - contacts
      - status
      - invoiceNumber
      - currencyCode
      - createdAt
      - dueAt
      - amount
      - dueAmount
    invoice_search_params:
      type: object
      properties:
        q:
          type: string
          nullable: true
        mode:
          type: string
          nullable: true
        f:
          type: object
          nullable: true
          properties:
            field:
              type: string
            value:
              type: string
        s:
          type: object
          nullable: true
          properties:
            field:
              type: string
            direction:
              type: string
    invoice_search_params_with_array_mode:
      type: object
      properties:
        q:
          type: string
          nullable: true
        mode:
          type: string
          nullable: true
        f:
          type: array
          nullable: true
          items:
            type: object
            properties:
              field:
                type: string
              value:
                type: string
        s:
          type: array
          nullable: true
          items:
            type: object
            properties:
              field:
                type: string
              direction:
                type: string
    country:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        alpha2:
          type: string
        dial_code:
          type: string
          nullable: true
      required:
      - id
      - name
      - alpha2
      - dial_code
    country_mapped:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        alpha2:
          type: string
        dialCode:
          type: string
          nullable: true
      required:
      - id
      - name
      - alpha2
      - dialCode
