shared:
  - accounts.larcity.ngrok.dev
development:
  - accounts.larcity
test:
  - accounts.larcity.ngrok.test
  - accounts.larcity.test
  - www.example.com
lab:
  - accounts.lab.larcity.dev
  - accounts.lab.larcity.tech
  - accounts.lab.larcity.hopto.org
staging:
  - cami-staging-app-ghexn.ondigitalocean.app
  - accounts.staging.lar.city
  - accounts.staging.larcity.org
  - accounts.staging.larcity.tech
  - accounts.staging.larcity.business
  - accounts.staging.larcity.hopto.org
  - accounts.larcity.dev
  - uches-m4-home-mini
  - uches-m4-home-mini.tail83bfcb.ts.net
  #- accounts.staging.madebylar.city
  #- accounts.staging.larcity.com
production:
  - larcity-production-app-98wcr.ondigitalocean.app
  - cami-production.onrender.com
  - accounts.larcity.hopto.org
  #- accounts.ho.lar.city
  - accounts.madebylar.city
#  - accounts.ho.larcity.business
  - accounts.larcity.com
  - accounts.larcity.tech
  - accounts.lar.city
  #- www.larcity.com
  #- www.lar.city
  #- larcity.com
  #- lar.city
