shared: &shared
  aliases:

development:
  aliases:

test:
  aliases:
    crm: <%= ENV.fetch('CONTAINER_REGISTRY_HOST') %>/twenty-crm
    web: <%= ENV.fetch('CONTAINER_REGISTRY_HOST') %>/cami-web
    worker: <%= ENV.fetch('CONTAINER_REGISTRY_HOST') %>/cami-worker

lab: &lab
  <<: *shared
  aliases:
    crm: <%= ENV.fetch('CONTAINER_REGISTRY_HOST') %>/twenty-crm-production
    web: <%= ENV.fetch('CONTAINER_REGISTRY_HOST') %>/cami-production
    worker: <%= ENV.fetch('CONTAINER_REGISTRY_HOST') %>/cami-production-worker

staging:
  <<: *lab

production:
  <<: *lab
