shared:
    # The shared section is used to define variables that are common across all environments.
    # These variables can be overridden in the environment-specific sections if needed.
    # For example, you can define a default domain name here and override it in the production section.

    - domain: larcity.org
      content: nas-1.ho
      type: A
      ttl: 1800

    - domain: larcity.org
      content: nas-2.ho
      type: A
      ttl: 1800

    - domain: larcity.org
      content: accounts.staging
      type: A
      ttl: 1800
