default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues:
        - critical
        - <%= `hostname`.strip %>
        - default
        - yeet
      threads: <%= ENV.fetch("RAILS_QUEUE_THREADS") { 2 } %>
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
