# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
development:
  update_serverinfo_metadata:
    class: Zoho::UpdateServerinfoMetadataJob
    queue: yeet
    # args: [ 1000, { batch_size: 500 } ]
    schedule: 0 5 * * 0 # every Sunday at 5am
