# On recurring tasks: https://github.com/rails/solid_queue?tab=readme-ov-file#recurring-tasks
common: &common
  update_serverinfo_metadata:
    class: Zoho::UpdateServerinfoMetadataJob
    queue: yeet
    # args: [ 1000, { batch_size: 500 } ]
    schedule: '0 5 * * 0' # every Sunday at 5am

  cleanup_retired_ddns_records_job:
    class: DDNS::CleanupRetiredRecordsJob
    queue: yeet
    # At every 15th minute past every hour from 7 through 10
    # and every hour from 18 through 22 on every day-of-week
    # from Monday through Saturday.
    schedule: '*/15 7-10,18-22 * * 1-6 America/New_York'

  fetch_paypal_invoices_job:
    class: PayPal::FetchInvoicesJob
    queue: default
    # At every 15th minute past every hour from 5 through 9,
    # every hour from 12 through 13, and every hour from 18 through 22
    # on every day-of-week from Monday through Saturday.
    schedule: '*/15 5-9,12-13,18-22 * * 1-6 America/New_York'

  upsert_invoice_records_job:
    class: UpsertInvoiceRecordsJob
    queue: yeet
    # At every 15th minute past every hour from 5 through 9,
    # every hour from 12 through 13, and every hour from 18 through 22
    # on every day-of-week from Monday through Saturday.
    schedule: '*/15 5-9,12-13,18-22 * * 1-6 America/New_York'

home_office: &home_office
  <<: *common
  ddns_update_job:
    class: DDNSUpsertJob
    queue: yeet
    # args: [ 1000, { batch_size: 500 } ]
    schedule: 'every 15 minutes America/New_York' # every 15 minutes

  update_default_url_options_job:
    class: UpdateDefaultURLOptionsJob
    queue: yeet
    # args: [ 1000, { batch_size: 500 } ]
    schedule: '*/5 6-21 * * *' # Every 5 minutes from 06:00 to 22:00 daily

development:
  <<: *common

staging:
  <<: *home_office

production:
  <<: *common
