# On recurring tasks: https://github.com/rails/solid_queue?tab=readme-ov-file#recurring-tasks
development:
  update_serverinfo_metadata:
    class: Zoho::UpdateServerinfoMetadataJob
    queue: yeet
    # args: [ 1000, { batch_size: 500 } ]
    schedule: "0 5 * * 0" # every Sunday at 5am

  fetch_paypal_invoices_job:
    class: PayPal::FetchInvoicesJob
    queue: default
    schedule: "45 5 * * 1-6" # At 05:45 from Monday to Saturday

  upsert_invoice_records_job:
    class: UpsertInvoiceRecordsJob
    queue: yeet
    schedule: "*/15 6-20 * * 1-6" # Every 15 minutes from 06:00 to 21:00 from Monday to Saturday
