# fly.toml app configuration file generated for cami-core
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cami-core"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.web"
  [build.args]
    RAILS_ENV = "production"

[env]
  PORT = "8080"
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
  RAILS_LOG_TO_STDOUT = "true"
  APP_CONFIG_CHECK_ENV_VARS = "yes"
  APP_PRIMARY_DATABASE_NAME = "cami_production"
  APP_DATABASE_USER = "postgres"

[processes]
  web = "bin/rails server"
  worker = "bin/jobs"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
